language: php

php:
  5.3
  5.4

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
  - php composer.phar install

script: php mageekguy.atoum.phar -d Tests/Units
